### ISSUE TITLE
VU accuracy

### ISSUE THREAD

**Issue by malradhi** [santi-pdp/msc_thesis#1]
Dear Santi,

Many thanks for sharing your MSc thesis which is very interesting and quite clear to understand.
The only think that I have not understood which is how did you calculate the voiced/unvoiced flag prediction accuracy according to the equation on page 59?

I would appreciate if you could explain it in more detail.

Thanks in advance and best regards.

**Comment by santi-pdp** [comment]
HI @Ali20177 ,

The voiced/unvoiced flag is a binary classification outcome, so its values are either 0 or 1. Now the accuracy measures how many correct hits we made, so how many coincidences we have of either 0 or 1 between predictions and groundtruth labels. In the equation there are 4 sub-metrics: True Positive, True Negative, False Positive, False Negative. 

- TP: How many actual 1 did the system predict as 1. 
- TN: How many actual 0 did the system predict as 0. 
- FN:  How many mistaken 0 did the system predict when they had to be 1. 
- FP:  How many mistaken 1 did the system predict when they had to be 0.

The equation is then a ratio between correctly predicted hits and total predictions. The higher the ratio, it's better predicting "True" labels either TP or TN. As an example, if we have the following groundtruth `y_g = [0, 0, 1, 1, 1, 0, 1]` and the predictions `y_p = [0, 1, 1, 1, 0, 1, 1]`, we have: `TP=3, TN=1, FP=2, FN=1, so Acc = 4/7 = 0.57 = 57%`, which turns out to be quite bad.

Regards

**Comment by malradhi** [comment]
Thank you very much indeed.
